### ISSUE TITLE
Change the state text field to a prepopulated dropdown

### ISSUE THREAD

**Issue by radius314** [LittleGreenViper/BMLT-Root-Server#26]
In order to keep people using a standard state code definition (which is used for reliability querying), Id like to be able to predefine the state / province drop down in the admin console to a list of values.  This could be in the auto-config.inc.php and just be an array.

**Comment by jbraswell** [comment]
Would you have a default list of states/provinces that you'd like the wizard to write to `auto-config.inc.php`, or would you just make this a hidden feature initially?

**Comment by radius314** [comment]
wizard?

**Comment by jbraswell** [comment]
Yes, when you first install the root server there is a wizard that walks you through configuration and auto-generation of `auto-config.inc.php`.

**Comment by radius314** [comment]
Would not have to be on the wizard IMO.  The issue that this would be solving is that people are entering all kinds of weird values for states “NC” or “North Carolina” and misspellings.  This throws of our querying by string capability.  

What I imagine is that you can just configure the field to be a dropdown instead of freeform text field.  Those values are pre-populated in the config.inc.php file.  Again not sure the wizard needs to be modified for this.

**Comment by LittleGreenViper** [comment]
I originally planned this, but be aware that the BMLT is not a US-only utility.

It becomes a VERY big deal to change the contents of the popup for different nations.

**Comment by LittleGreenViper** [comment]
We can't forget that a huge "selling point" of the BMLT, is its extreme flexibility in working forn non-US Service bodies.

Whenever I do work, I always keep one word in mind:

"Iran".

**Comment by radius314** [comment]
I actually see this as extremely flexible.  It's an option that is in the configuration.  This feature should not affect anyone that doesn't want to use it.

**Comment by pjaudiomv** [comment]
this feature would be nice for the county, and country fields too.

**Comment by LittleGreenViper** [comment]
One of the things that you need to be VERY careful of, here, is that the "solutions" to these problems often becomes "bring in a dependency!"

Some of these dependencies are a VERY BAD THING. One of the ways that the "big kids on the block" have achieved supremacy is to write libraries and frameworks that make it easy to do stuff.

I am immediately suspicious of anything provided by Facebook. Google is a bit better, but mostly because they don't really get into the data stream (they don't really need to).

Something like GraphQL is smack-dab in the middle of your data stream. Facebook gets a peek at every bit of data that goes through your site, and they will use it. Don't believe them for a second when they say they won't use it. They are proven sociopaths. Google is just as bad, but you can sequester the service they provide (for now -note what has already happened with the Maps API). I am extremely suspicious of OAuth2 SSO solutions.

A big part of what has been going on the last few years, is that an entire generation of programmers has been raised in an environment where they -quite literally- cannot write dependency-free software. It's really depressing.

I was at a GraphQL demo a month or so ago, and the kid giving the demo had half a dozen dependencies in the software he was using for the demo. It was ostensibly about GraphQL, but what he was really demonstrating was GraphQL Yoga, and he barely mentioned that. It was just assumed that the baseline was Yoga. What he was demonstrating would ONLY work in Yoga. It was not GraphQL.

That's crazy, but it's par for the course, these days.

**Comment by radius314** [comment]
This looks good to me.  This will really help data quality.

**Comment by pjaudiomv** [comment]
this could be problematic for people using the BMLT Administrator iOS app, server admins should still  watch data for variations from set array if using this.

**Comment by radius314** [comment]
There was a discussion on Slack about modifying the iOS app.

**Comment by jbraswell** [comment]
This is done in 2.12.0

**Comment by jbraswell** [comment]
Still need to validate that this doesn’t break the iOS app. Might be worth implementing the drop down in the iOS app.

**Comment by LittleGreenViper** [comment]
It shouldn't, as it becomes a text string, but I don't have the bandwidth to do it quite yet (I will, though; just not for a while -I need to reinvent myself again, and that takes time).
